### PR TITLE
ovl/sctp: add a send-one-packet command

### PR DESCRIPTION
**Pull request by uablrek**
Support sending one packet with a specified size. This is intended for fragment tests

### CODE REVIEW

**Comment by sriramy** [comment]
Do you think it is worthwhile to add --count parameter to specify how many packets to send? I can merge this if you think it is unnecessary.

**Comment by uablrek** [comment]
No, not really. The "ctraffic" functions can be used to send many packets. This is mainly to make a capture with "tcpdump" and see what happens. For instance I observed that SCPT doesn't use ip-fragments locally, it checks the MTU of the outgoing interface and segments large packets on SCTP level. I didn't know that, and it may be a lksctp unique feature.

**Comment by uablrek** [comment]
Without this function I tested with interactive interface and pasted a very large blob-o-text :smile:

**Comment by sriramy** [comment]
Ok I understand. Will merge it now

**Pull request merged**
