### PR TITLE
Refresh private registry

### PR DESCRIPTION
**Pull request by uablrek**
To use port 80 in the container removes the need to map port 5000 to port 80 on the host.

The documentation is basically rewritten, and loading over IPv6 works.

ovl/images is updated to handle lreg on port 80 (default), also several "lreg_*" commands now handles multiple ovl's on the command line, or none.

An important update in ovl/images is that the "pause" image now is loaded on a "images lreg_preload". It became important when the pre-pulled images were removed.

### CODE REVIEW

**Comment by uablrek** [comment]
@sriramy please check `ovl/private-reg/default/etc/init.d/28private-reg.rc` script. I handle ipv6 separately, but I think the `/etc/containers/registries.conf` script can be the same for ipv4 and ipv6, and contain `example.com` instead of an actual ip-address.

**Comment by sriramy** [comment]
The docker registry opens up ::80 on the host regardless, of what port the container is running on. We can actually use port 80 any address on the host namespace to reach the registry.
If we just use the Gateway/IPv6Gateway address in xcluster always, it really doesn't matter what container port we use?

```
cmd_lreg_ip() {
	if test -n "$LOCAL_REGISTRY"; then
		echo $LOCAL_REGISTRY
		return 0
	fi
	local regip=$(docker inspect registry | jq -r .[0].NetworkSettings.Gateway)
	test -n "$regip" || die "Can't get address of the local registry"
	echo $regip
}
```

This is the output from my local docker registry.
```
docker inspect registry | jq -r .[0].NetworkSettings.Gateway
172.17.0.1
docker inspect registry | jq -r .[0].NetworkSettings.IPv6Gateway
fd00:2008::1
```

**Comment by uablrek** [comment]
With the registry running:
```
# netstat -putln | grep :80
tcp6       0      0 :::8080                 :::*                    LISTEN      6005/java           
```
So, no port 80 is only opened in the registry container netns:
```
~ > docker exec -it registry netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 :::80                   :::*                    LISTEN      
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
```

**Comment by uablrek** [comment]
The `.[0].NetworkSettings.Gateway` is the address of `docker0` in host netns. If you use it, you must have a port mapping.

So, the address of the registry docker container must be used. It's kind of the whole point of this PR.

**Comment by uablrek** [comment]
Please note that the `-p` option is removed from the registry start:
Before:
```
docker run -d --restart=always --name registry -p 80:5000 registry:2
```
(port 80 is taken in main netns)

Now:
```
docker run -d --restart=always --name registry -e REGISTRY_HTTP_ADDR=:80 registry:2
```

**Comment by uablrek** [comment]
Unfortunately `skopeo` can't handle ipv6 addresses, https://github.com/containers/image/issues/1004, and probably never will.

So for image loading IPv4 must be used :-1: 

But at image pull to an `xcluster` works at least.

**Comment by sriramy** [comment]
> The `.[0].NetworkSettings.Gateway` is the address of `docker0` in host netns. If you use it, you must have a port mapping.
> 
> So, the address of the registry docker container must be used. It's kind of the whole point of this PR.

Ok, if we don't want to have a port mapping, of course we have to use the address of the container, and for pulls to docker.io/k8s.io to work we should run on port 80.

**Comment by sriramy** [comment]
It works for my environment, so we can merge this if you think it is ready.

**Comment by uablrek** [comment]
Let me update the doc's with the skopeo limitation...

**Comment by uablrek** [comment]
A reason is that I think many people have some web-server installed for various reasons, and a port-map to 80 creates a conflict.

**Comment by sriramy** [comment]
> A reason is that I think many people have some web-server installed for various reasons, and a port-map to 80 creates a conflict.

Yes, that makes sense!

**Comment by uablrek** [comment]
> Let me update the doc's with the skopeo limitation...

@sriramy done.

**Comment by sriramy** [comment]
Really awesome work :)

**Pull request merged**
