### PR TITLE
Remove pre-pulled images

### PR DESCRIPTION
**Pull request by uablrek**
The build and release procedure is heavily updated and is described in doc/build.md

`xcadmin.sh` is simplified and the size of the release archive has gone down from ~150MB to ~50MB.

### CODE REVIEW

**Comment by uablrek** [comment]
Well, a private registry _really_ makes a difference! Now "xcadmin test" does not implicitly set private-reg, you must do:
```
export XOVLS=private-reg
```
In main netns tests times out without private-reg, but things start eventually (after several minutes)

**Comment by sriramy** [comment]
Tested by creating a new workspace and release using this PR.
Can we merge this?

**Comment by uablrek** [comment]
>  Can we merge this?

Yes, IMO. Afaik we are the main users of `xcluster`, but if you can build K8s images on v1.25.2, upload them, and update the wiki, it would be good.

**Comment by uablrek** [comment]
I want changed the link to hd-k8s-xcluster* to soft links, and I want to remove them entirely. I delete them in my env to detect if I am still using them somewhere.

**Comment by sriramy** [comment]
> > Can we merge this?
> 
> Yes, IMO. Afaik we are the main users of `xcluster`, but if you can build K8s images on v1.28.2, upload them, and update the wiki, it would be good.

Yes, I can do that today.

**Pull request merged**
