### PR TITLE
Upgrade to linux-6.5

### PR DESCRIPTION
**Pull request by uablrek**
right

### CODE REVIEW

**Comment by uablrek** [comment]
There may be a problem with K8s CNI-plugin Antrea with IPv6. Hold for now...

**Comment by sriramy** [comment]
> There may be a problem with K8s CNI-plugin Antrea with IPv6. Hold for now...
> 
> #### Update
> Yes, seems to be the kernel version. I don't wanna bisect 😢 Antrea/IPv6 works with `linux-6.4.12` but not with `linux-6.5`.

Ok, I can take a look at Antrea. What seems to the problem? Any specific test case that fails?

**Comment by uablrek** [comment]
The problem in short; when accessing a service via the clusterIP in a IPv6 based cluster from within a POD, there is no distribution. All connections end up in the same server POD.

Distribution works to the same service from main netns on a node (or from a POD with "hostNetwork:true", and everything works fine in an IPv4 based cluster.

It doesn't seem related to Antrea, I tested to [upgrade to v1.13.0](https://github.com/Nordix/xcluster/pull/55), but it's something that has happened in the kernel.

It can be some different kernel configuration that is needed that basically only affects `xcluster` and others building their own kernel.

**Comment by sriramy** [comment]
Ok, looks similar to the ECMP problem I have been chasing. Hopefully that gets merged today.
I can take a look at this later today, if you have still not found the problem ..

**Comment by sriramy** [comment]
Ok, then I wait until we get some response from Antrea to look at this. We can meanwhile merge this, and raise an xcluster issue to track this problem?

**Comment by uablrek** [comment]
> Ok, then I wait until we get some response from Antrea to look at this. We can meanwhile merge this, and raise an xcluster issue to track this problem?

Sure. I "un-draft" it

**Pull request merged**
