### PR TITLE
Remove FIRST_WORKER

### PR DESCRIPTION
**Pull request by uablrek**
* New functions added in ovl/test k8s_nodes(), k8s_workers() and k8s_masters()
* Update "xcadmin k8s_test"
* Remove FIRST_WORKER from ovl's

### CODE REVIEW

**Comment by uablrek** [comment]
I got a bit medieval on `ovl/usrsctp`, but is didn't work in the first place. @sriramy Please take a look if you like, otherwise we can fix it later.

**Comment by uablrek** [comment]
I plan to fix ovl/k8s-xcluster, with master outside the cluster, in a separate PR. For instance all ovl/k8s-cni-* and ovl's crio and containerd must be updated in some (yet unknown) way to get ovl/k8s-xcluster working.

I leave ovl/k8s-xcluster broken for now, but remove the draft/WIP

**Comment by uablrek** [comment]
Or move ovl/k8s-xcluster to attic/ and add a ovl/k8s-ha ...

**Comment by sriramy** [comment]
> I got a bit medieval on `ovl/usrsctp`, but is didn't work in the first place. @sriramy Please take a look if you like, otherwise we can fix it later.

Let's fix it later, usrsctp ovl needs an overhaul anyhow.

**Comment by uablrek** [comment]
After some thought I decided to move `ovl/k8s-xcluster` to attic/. Nobody will maintain it anyway.

I am thinking of adding a `FIRST_NODE` to replace `FIRST_WORKER` with about the same function, but better specified. It can be used to "free" some VMs, for instance for a redundant etcd setup for HA.

**Comment by sriramy** [comment]
A new ovl to define the vm roles within k8s? Or to define the k8s topology?
Anyhow, is this ready to merge now?

**Comment by uablrek** [comment]
Yes, ready to merge. I use it on a local branch myself.

I want to be able to have some VMs in the same "tier" as cluster VMs (001-200) but outside K8s. My first thought was to reserve for instance vm-001 -- vm-003 for "something else" (e.g. HAproxy's or etcd for a K8s ha-setup). But thinking more, it seems a bad idea. Better to keep everything as-is and use for instance vm-191 -- vm-200 in individual ovl's where they are needed, and not tamper with anything else. A problem is "xc stop" which currently only stop _some_ VMs, not all 001-200 (which takes an irritating amount of time). But I am not happy with that anyway. Which VMs that are started should be remembered somewhere (where the disk-overlays are stored for instance), and "xc stop" (and internal functions) should stop only the started VMs.

**Comment by uablrek** [comment]
As a side-note: At some point the limit #VMs <= 256 may be addressed (not a limitation in my setups yet), but the limit is actually 100 since gnu `screen` have a max-limit of 100. Now, that can be configured ad build-time, but better to seek an alternative to screen, like a simple pipe or something

**Comment by sriramy** [comment]
I will create issues to remember to solve these, else I forget

**Pull request merged**
